/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _HistoryRoute } from '../pages/history';
import { Route as _IndexRoute } from '../pages/';
import { Route as _InfoRoute } from '../pages/info';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/history': (typeof _HistoryRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/info': (typeof _InfoRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/history': (typeof _HistoryRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/info': (typeof _InfoRoute)['_outputType'];
  }
}
